/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author DIEGO
 */
public class Ventana extends javax.swing.JFrame {

    private final Controlador controlador;
    
    public Ventana(Controlador controlador) {
        initComponents();
        
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jitInicio = new javax.swing.JInternalFrame();
        jpInicio = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlblNombresApellidos1 = new javax.swing.JLabel();
        jlblNombreUsuario1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGenerarPlanilla = new javax.swing.JButton();
        btnAnularContrato = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnRegistrarUgel = new javax.swing.JButton();
        btnRegistrarPago = new javax.swing.JButton();
        btnRegistrarContrato = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        jitFormularios = new javax.swing.JInternalFrame();
        jdpFormularios = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setLayout(new java.awt.CardLayout());

        jitInicio.setTitle("Inicio");
        jitInicio.setVisible(true);

        jpInicio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/admin.png"))); // NOI18N

        jlblNombresApellidos1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblNombresApellidos1.setForeground(new java.awt.Color(255, 255, 255));
        jlblNombresApellidos1.setText("Usuario");

        jlblNombreUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jlblNombreUsuario1.setText("nombre de usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblNombresApellidos1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(jlblNombreUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jlblNombresApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblNombreUsuario1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.setActionCommand("Administrativos");
        btnRegistrarCliente.setBorderPainted(false);
        btnRegistrarCliente.setContentAreaFilled(false);
        btnRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCliente.setFocusPainted(false);
        btnRegistrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGenerarPlanilla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerarPlanilla.setText("Generar Planilla");
        btnGenerarPlanilla.setBorderPainted(false);
        btnGenerarPlanilla.setContentAreaFilled(false);
        btnGenerarPlanilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarPlanilla.setFocusPainted(false);
        btnGenerarPlanilla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarPlanilla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGenerarPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPlanillaActionPerformed(evt);
            }
        });

        btnAnularContrato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnularContrato.setText("Anular Contrato");
        btnAnularContrato.setBorderPainted(false);
        btnAnularContrato.setContentAreaFilled(false);
        btnAnularContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnularContrato.setFocusPainted(false);
        btnAnularContrato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnularContrato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnularContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularContratoActionPerformed(evt);
            }
        });

        btnModificarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificarCliente.setText("Modificar Cliente");
        btnModificarCliente.setBorderPainted(false);
        btnModificarCliente.setContentAreaFilled(false);
        btnModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCliente.setFocusPainted(false);
        btnModificarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        btnRegistrarUgel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarUgel.setText("Registrar Ugel");
        btnRegistrarUgel.setBorderPainted(false);
        btnRegistrarUgel.setContentAreaFilled(false);
        btnRegistrarUgel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarUgel.setFocusPainted(false);
        btnRegistrarUgel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarUgel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarUgel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUgelActionPerformed(evt);
            }
        });

        btnRegistrarPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarPago.setText("Registrar Pago");
        btnRegistrarPago.setBorderPainted(false);
        btnRegistrarPago.setContentAreaFilled(false);
        btnRegistrarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarPago.setFocusPainted(false);
        btnRegistrarPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarPago.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        btnRegistrarContrato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarContrato.setText("Registrar Contrato");
        btnRegistrarContrato.setBorderPainted(false);
        btnRegistrarContrato.setContentAreaFilled(false);
        btnRegistrarContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarContrato.setFocusPainted(false);
        btnRegistrarContrato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarContrato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarContratoActionPerformed(evt);
            }
        });

        btnGenerarReporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.setBorderPainted(false);
        btnGenerarReporte.setContentAreaFilled(false);
        btnGenerarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarReporte.setFocusPainted(false);
        btnGenerarReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarUgel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnularContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGenerarPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarCliente)
                    .addComponent(btnModificarCliente)
                    .addComponent(btnRegistrarContrato))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarPlanilla)
                    .addComponent(btnAnularContrato)
                    .addComponent(btnRegistrarUgel)
                    .addComponent(btnGenerarReporte))
                .addGap(47, 47, 47)
                .addComponent(btnSalir)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpInicioLayout = new javax.swing.GroupLayout(jpInicio);
        jpInicio.setLayout(jpInicioLayout);
        jpInicioLayout.setHorizontalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpInicioLayout.setVerticalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jitInicioLayout = new javax.swing.GroupLayout(jitInicio.getContentPane());
        jitInicio.getContentPane().setLayout(jitInicioLayout);
        jitInicioLayout.setHorizontalGroup(
            jitInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jitInicioLayout.setVerticalGroup(
            jitInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jitInicioLayout.createSequentialGroup()
                .addComponent(jpInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.add(jitInicio, "card3");

        jitFormularios.setVisible(true);

        jdpFormularios.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jdpFormulariosLayout = new javax.swing.GroupLayout(jdpFormularios);
        jdpFormularios.setLayout(jdpFormulariosLayout);
        jdpFormulariosLayout.setHorizontalGroup(
            jdpFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        jdpFormulariosLayout.setVerticalGroup(
            jdpFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jitFormulariosLayout = new javax.swing.GroupLayout(jitFormularios.getContentPane());
        jitFormularios.getContentPane().setLayout(jitFormulariosLayout);
        jitFormulariosLayout.setHorizontalGroup(
            jitFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jitFormulariosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jdpFormularios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jitFormulariosLayout.setVerticalGroup(
            jitFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jitFormulariosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jdpFormularios)
                .addContainerGap())
        );

        jDesktopPane1.add(jitFormularios, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jDesktopPane1)
                    .addGap(8, 8, 8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void cerrarFormulario() {
        jitFormularios.setVisible(false);
        jitInicio.setVisible(true);
    }
    
    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioVistaReporte formularioGenerarReporte = new FormularioVistaReporte(this);
        this.jdpFormularios.add(formularioGenerarReporte);
        formularioGenerarReporte.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnRegistrarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarContratoActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioRegistrarContrato formularioRegistrarContrato = new FormularioRegistrarContrato(this);
        this.jdpFormularios.add(formularioRegistrarContrato);
        formularioRegistrarContrato.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnRegistrarContratoActionPerformed

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioRegistrarPago formularioRegistrarPago = new FormularioRegistrarPago(this);
        this.jdpFormularios.add(formularioRegistrarPago);
        formularioRegistrarPago.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    private void btnRegistrarUgelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUgelActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioRegistrarUgel formularioRegistrarUgel = new FormularioRegistrarUgel(this);
        this.jdpFormularios.add(formularioRegistrarUgel);
        formularioRegistrarUgel.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnRegistrarUgelActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioModificarCliente formularioModificarCliente = new FormularioModificarCliente(this);
        this.jdpFormularios.add(formularioModificarCliente);
        formularioModificarCliente.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnAnularContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularContratoActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioAnularContrato formularioAnularContrato = new FormularioAnularContrato(this);
        this.jdpFormularios.add(formularioAnularContrato);
        formularioAnularContrato.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnAnularContratoActionPerformed

    private void btnGenerarPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPlanillaActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioGenerarPlanilla formularioGenerarPlanilla = new FormularioGenerarPlanilla(this);
        this.jdpFormularios.add(formularioGenerarPlanilla);
        formularioGenerarPlanilla.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnGenerarPlanillaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        this.jitInicio.setVisible(false);
        this.jitFormularios.setVisible(true);
        
        FormularioRegistrarCliente formularioRegistrarCliente = new FormularioRegistrarCliente(this);
        this.jdpFormularios.add(formularioRegistrarCliente);
        formularioRegistrarCliente.rellenar(true,this.controlador);
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ventana().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularContrato;
    private javax.swing.JButton btnGenerarPlanilla;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarContrato;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JButton btnRegistrarUgel;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JDesktopPane jdpFormularios;
    private javax.swing.JInternalFrame jitFormularios;
    private javax.swing.JInternalFrame jitInicio;
    private javax.swing.JLabel jlblNombreUsuario1;
    private javax.swing.JLabel jlblNombresApellidos1;
    private javax.swing.JPanel jpInicio;
    // End of variables declaration//GEN-END:variables
}
